<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AdminProfileSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('admin_profiles')->insert([
            [
                'admin_id' => 1,
                'lastname' => '栫',
                'firstname' => '勝宏',
                'lastname_kana' => 'カコイ',
                'firstname_kana' => 'カツヒロ',
                'admin_photo_path' => null,
                'birth' => '1981-12-15',
                'gender' => '男',
                'zipcode' => '6308303',
                'address1' => '奈良県',
                'address2' => '奈良市',
                'address3' => '南紀寺町',
                'address4' => '2丁目274-3萠黄アパート103号',
                'phone_number' => '090-9580-9257',
                'mobile_number' => '090-9580-9257',
                'website' => 'https://katsu-coach.com/',
                'facebook' => 'https://www.facebook.com/katsuhiro.kakoi/',
                'twitter' => 'https://twitter.com/KatsuhiroKakoi',
                'instagram' => 'https://www.instagram.com/katsuhiro.k1215/',
                'youtube' => 'https://www.youtube.com/channel/UC1wqTr1OLcwdT_iyPUR_QKQ',
                'line' => null,
                'admin_no' => '0001',
                'serial_no' => '0001',
                'start_date' => '2023-06-01',
            ],
            [
                'admin_id' => 2,
                'lastname' => '中村',
                'firstname' => '英史',
                'lastname_kana' => 'ナカムラ',
                'firstname_kana' => 'ヒデトシ',
                'admin_photo_path' => null,
                'birth' => '1979-02-23',
                'gender' => '男',
                'zipcode' => '5310072',
                'address1' => '大阪府',
                'address2' => '大阪市北区',
                'address3' => '豊崎',
                'address4' => '1-3-11',
                'phone_number' => '0663742788',
                'mobile_number' => '0663742788',
                'website' => null,
                'facebook' => null,
                'twitter' => null,
                'instagram' => null,
                'youtube' => null,
                'line' => null,
                'admin_no' => '0002',
                'serial_no' => '0002',
                'start_date' => '2023-09-01',
            ],
            [
                'admin_id' => 3,
                'lastname' => '近藤',
                'firstname' => '伸洋',
                'lastname_kana' => 'コンドウ',
                'firstname_kana' => 'ノブヒロ',
                'admin_photo_path' => null,
                'birth' => '1979-02-23',
                'gender' => '男',
                'zipcode' => '5310072',
                'address1' => '大阪府',
                'address2' => '大阪市北区',
                'address3' => '豊崎',
                'address4' => '1-3-11',
                'phone_number' => '0663742788',
                'mobile_number' => '0663742788',
                'website' => null,
                'facebook' => null,
                'twitter' => null,
                'instagram' => null,
                'youtube' => null,
                'line' => null,
                'admin_no' => '0003',
                'serial_no' => '0003',
                'start_date' => '2023-09-01',
            ],
            [
                'admin_id' => 4,
                'lastname' => '大谷',
                'firstname' => '加奈子',
                'lastname_kana' => 'オオタニ',
                'firstname_kana' => 'カナコ',
                'admin_photo_path' => null,
                'birth' => '1979-02-23',
                'gender' => '女',
                'zipcode' => '5310072',
                'address1' => '大阪府',
                'address2' => '大阪市北区',
                'address3' => '豊崎',
                'address4' => '1-3-11',
                'phone_number' => '0663742788',
                'mobile_number' => '0663742788',
                'website' => null,
                'facebook' => null,
                'twitter' => null,
                'instagram' => null,
                'youtube' => null,
                'line' => null,
                'admin_no' => '0004',
                'serial_no' => '0004',
                'start_date' => '2023-09-01',
            ],
            [
                'admin_id' => 5,
                'lastname' => '中村',
                'firstname' => '周平',
                'lastname_kana' => 'ナカムラ',
                'firstname_kana' => 'シュウヘイ',
                'admin_photo_path' => null,
                'birth' => '1979-02-23',
                'gender' => '男',
                'zipcode' => '6610976',
                'address1' => '兵庫県',
                'address2' => '尼崎市',
                'address3' => '潮江',
                'address4' => '1丁目16番1号 アミング潮江ウエスト二番館201-6',
                'phone_number' => '0649506939',
                'mobile_number' => '0649506939',
                'website' => null,
                'facebook' => null,
                'twitter' => null,
                'instagram' => 'https://www.instagram.com/shuhei.nakamura.900/',
                'youtube' => null,
                'line' => null,
                'admin_no' => '0005',
                'serial_no' => '0005',
                'start_date' => '2023-09-01',
            ],
            [
                'admin_id' => 6,
                'lastname' => '相賀',
                'firstname' => '翔斗',
                'lastname_kana' => 'アイガ',
                'firstname_kana' => 'ショウマ',
                'admin_photo_path' => null,
                'birth' => '1979-02-23',
                'gender' => '男',
                'zipcode' => '6610976',
                'address1' => '兵庫県',
                'address2' => '尼崎市',
                'address3' => '潮江',
                'address4' => '1丁目16番1号 アミング潮江ウエスト二番館201-6',
                'phone_number' => '0649506939',
                'mobile_number' => '0649506939',
                'website' => null,
                'facebook' => null,
                'twitter' => null,
                'instagram' => null,
                'youtube' => null,
                'line' => null,
                'admin_no' => '0006',
                'serial_no' => '0006',
                'start_date' => '2023-09-01',
            ],
        ]);
    }
}
