<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CourseCategorySeeder extends Seeder
{
    public function run(): void
    {
        DB::table('course_categories')->insert([
            [
                'lesson_id' => 1,
                'type' => '一般教室',
                'name' => '一般教室',
                'description' => '会員制の一般教室です。',
                'course_category_photo_path' => null,
                'status' => true,
                'start_date' => '2023-05-01',
                'end_date' => '2025-03-31',
            ],
            [
                'lesson_id' => 1,
                'type' => '体験教室',
                'name' => '2023年プレ・オープン体験教室',
                'description' => '2023年プレ・オープン体験教室です。',
                'course_category_photo_path' => null,
                'status' => false,
                'start_date' => '2023-04-01',
                'end_date' => '2023-04-16',
            ],
            [
                'lesson_id' => 1,
                'type' => '体験教室',
                'name' => '2023年プレ・オープン2週間体験教室',
                'description' => '2023年プレ・オープン2週間体験教室です。',
                'course_category_photo_path' => null,
                'status' => false,
                'start_date' => '2023-04-17',
                'end_date' => '2023-04-30',
            ],
            [
                'lesson_id' => 1,
                'type' => '短期教室',
                'name' => '2023年プレ・オープン3日間短期教室',
                'description' => '2023年プレ・オープン3日間短期教室です。',
                'course_category_photo_path' => null,
                'status' => false,
                'start_date' => '2023-05-03',
                'end_date' => '2023-05-05',
            ],
            [
                'lesson_id' => 1,
                'type' => '体験教室',
                'name' => '2023年夏の無料体験教室',
                'description' => '2023年夏の無料体験教室です。',
                'course_category_photo_path' => null,
                'status' => false,
                'start_date' => '2023-07-24',
                'end_date' => '2023-08-23',
            ],
            [
                'lesson_id' => 1,
                'type' => '短期教室',
                'name' => '2023年夏の短期教室',
                'description' => '2023年夏の短期教室です。',
                'course_category_photo_path' => null,
                'status' => false,
                'start_date' => '2023-08-07',
                'end_date' => '2023-08-09',
            ],
            [
                'lesson_id' => 1,
                'type' => '体験教室',
                'name' => '2023年9月秋の体験教室',
                'description' => '2023年9月秋の体験教室です。',
                'course_category_photo_path' => null,
                'status' => false,
                'start_date' => '2023-09-23',
                'end_date' => '2023-09-24',
            ],
            [
                'lesson_id' => 1,
                'type' => '体験教室',
                'name' => '2023年10月秋の体験教室',
                'description' => '2023年10月秋の体験教室です。',
                'course_category_photo_path' => null,
                'status' => false,
                'start_date' => '2023-10-09',
                'end_date' => '2023-10-09',
            ],
            [
                'lesson_id' => 1,
                'type' => '体験教室',
                'name' => '2023年11月秋の体験教室',
                'description' => '2023年11月秋の体験教室です。',
                'course_category_photo_path' => null,
                'status' => false,
                'start_date' => '2023-11-03',
                'end_date' => '2023-10-05',
            ],
            [
                'lesson_id' => 1,
                'type' => 'イベント',
                'name' => '2024年クリスマス会',
                'description' => '2024年クリスマス会です。',
                'course_category_photo_path' => null,
                'status' => false,
                'start_date' => '2024-12-23',
                'end_date' => '2025-12-24',
            ],
            [
                'lesson_id' => 1,
                'type' => '体験教室',
                'name' => '2024年春の無料体験教室',
                'description' => '2024年春の無料体験教室です。',
                'course_category_photo_path' => null,
                'status' => false,
                'start_date' => '2024-03-23',
                'end_date' => '2024-03-31',
            ],
            [
                'lesson_id' => 1,
                'type' => '体験教室',
                'name' => '2024年GW体験教室',
                'description' => '2024年GW開催の体験教室です。',
                'course_category_photo_path' => null,
                'status' => false,
                'start_date' => '2024-04-29',
                'end_date' => '2024-05-06',
            ],
            [
                'lesson_id' => 1,
                'type' => '体験教室',
                'name' => '2024年夏の無料体験教室',
                'description' => '2024年夏の無料体験教室です。',
                'course_category_photo_path' => null,
                'status' => false,
                'start_date' => '2024-07-26',
                'end_date' => '2024-07-31',
            ],
            [
                'lesson_id' => 1,
                'type' => '短期教室',
                'name' => '2024年夏の短期教室',
                'description' => '2024年夏の短期教室です。',
                'course_category_photo_path' => null,
                'status' => false,
                'start_date' => '2024-08-05',
                'end_date' => '2024-08-21',
            ],
            [
                'lesson_id' => 1,
                'type' => '体験教室',
                'name' => '通常クラス体験教室',
                'description' => '通常クラスの体験教室です。',
                'course_category_photo_path' => null,
                'status' => true,
                'start_date' => '2024-10-01',
                'end_date' => '2025-03-31',
            ],
            [
                'lesson_id' => 2,
                'type' => '一般教室',
                'name' => '一般教室',
                'description' => '会員制の一般教室です。',
                'course_category_photo_path' => null,
                'status' => true,
                'start_date' => '2024-09-01',
                'end_date' => '2025-03-31',
            ],
            [
                'lesson_id' => 2,
                'type' => '体験教室',
                'name' => '通常クラス体験教室',
                'description' => '通常クラスの体験教室です。',
                'course_category_photo_path' => null,
                'status' => true,
                'start_date' => '2023-09-01',
                'end_date' => '2025-03-31',
            ],
            [
                'lesson_id' => 1,
                'type' => '体験教室',
                'name' => '2024年秋の無料体験教室',
                'description' => '2024年秋の無料体験教室です。',
                'course_category_photo_path' => null,
                'status' => false,
                'start_date' => '2023-11-03',
                'end_date' => '2024-11-04',
            ],
        ]);
    }
}
