<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CourseSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('courses')->insert([
            [
                'lesson_id' => 1,
                'course_category_id' => 1,
                'name' => '年少・年中コース',
                'description' => '幼稚園の年少・年中が対象のコースです。',
                'course_photo_path' => null,
                'status' => true,
                'application_start_date' => '2023-05-01 10:00:00',
                'application_end_date' => '2025-03-31 22:00:00',
                'sort_no' => 1,
            ],
            [
                'lesson_id' => 1,
                'course_category_id' => 1,
                'name' => '年長・1年生コース',
                'description' => '幼稚園の年長、小学生の1年生が対象のコースです。',
                'course_photo_path' => null,
                'status' => true,
                'application_start_date' => '2023-05-01 10:00:00',
                'application_end_date' => '2025-03-31 22:00:00',
                'sort_no' => 2,
            ],
            [
                'lesson_id' => 1,
                'course_category_id' => 1,
                'name' => '2年・3年生コース',
                'description' => '小学生の2年生・3年生が対象のコースです。',
                'course_photo_path' => null,
                'status' => false,
                'application_start_date' => '2023-05-01 10:00:00',
                'application_end_date' => '2024-01-31 22:00:00',
                'sort_no' => 3,
            ],
            [
                'lesson_id' => 1,
                'course_category_id' => 1,
                'name' => '小学生コース',
                'description' => '小学生のみが対象のコースです。',
                'course_photo_path' => null,
                'status' => true,
                'application_start_date' => '2023-05-01 10:00:00',
                'application_end_date' => '2025-03-31 22:00:00',
                'sort_no' => 4,
            ],
            [
                'lesson_id' => 1,
                'course_category_id' => 1,
                'name' => '小学・中学生コース',
                'description' => '小学生の4年生から中学生が対象のコースです。',
                'course_photo_path' => null,
                'status' => true,
                'application_start_date' => '2023-05-01 10:00:00',
                'application_end_date' => '2025-03-31 22:00:00',
                'sort_no' => 5,
            ],
            [
                'lesson_id' => 1,
                'course_category_id' => 1,
                'name' => 'キッズアクロコース',
                'description' => '幼稚園の年中から、小学生の3年生までを対象としたアクロバットコースです。アクロバットクラスはお申込条件として、「壁に倒立ができる」「側転」「ブリッジができる」お子様を対象とさせていただきます。主に、マット運動での技の習得を目指します。',
                'course_photo_path' => null,
                'status' => true,
                'application_start_date' => '2023-05-01 10:00:00',
                'application_end_date' => '2025-03-31 22:00:00',
                'sort_no' => 6,
            ],
            [
                'lesson_id' => 1,
                'course_category_id' => 1,
                'name' => 'アクロバットコース',
                'description' => '小学生の4年生から中学生が対象としたアクロバットコースです。アクロバットクラスはお申込条件として、「壁に倒立ができる」「側転」「ブリッジができる」お子様を対象とさせていただきます。主に、マット運動での技の習得を目指します。',
                'course_photo_path' => null,
                'status' => true,
                'application_start_date' => '2023-05-01 10:00:00',
                'application_end_date' => '2025-03-31 22:00:00',
                'sort_no' => 7,
            ],
            [
                'lesson_id' => 1,
                'course_category_id' => 11,
                'name' => '親子体操クラス',
                'description' => '親子体操のコースです。',
                'course_photo_path' => null,
                'status' => true,
                'application_start_date' => '2024-02-26 10:00:00',
                'application_end_date' => '2024-03-30 22:00:00',
                'sort_no' => 1,
            ],
            [
                'lesson_id' => 1,
                'course_category_id' => 11,
                'name' => '新年少・年中・年長クラス',
                'description' => '2024年度、新年少・年中・年長の体験クラスです。',
                'course_photo_path' => null,
                'status' => false,
                'application_start_date' => '2024-02-26 10:00:00',
                'application_end_date' => '2024-03-30 22:00:00',
                'sort_no' => 2,
            ],
            [
                'lesson_id' => 1,
                'course_category_id' => 11,
                'name' => '新1年・小学生・中学生クラス',
                'description' => '新1年生から中学生までの体験クラスです。',
                'course_photo_path' => null,
                'status' => false,
                'application_start_date' => '2024-02-26 10:00:00',
                'application_end_date' => '2024-03-30 22:00:00',
                'sort_no' => 3,
            ],
            [
                'lesson_id' => 1,
                'course_category_id' => 11,
                'name' => 'アクロバットクラス',
                'description' => 'アクロバットの体験クラスです。',
                'course_photo_path' => null,
                'status' => false,
                'application_start_date' => '2024-02-26 10:00:00',
                'application_end_date' => '2024-03-30 22:00:00',
                'sort_no' => 4,
            ],
            [
                'lesson_id' => 1,
                'course_category_id' => 11,
                'name' => '新1年・小学生・中学生クラス',
                'description' => '新1年生から中学生までの体験クラスです。',
                'course_photo_path' => null,
                'status' => false,
                'application_start_date' => '2024-02-26 10:00:00',
                'application_end_date' => '2024-03-30 22:00:00',
                'sort_no' => 5,
            ],
            [
                'lesson_id' => 1,
                'course_category_id' => 15,
                'name' => '親子体操クラス',
                'description' => '親子体操のコースです。',
                'course_photo_path' => null,
                'status' => false,
                'application_start_date' => '2024-01-28 10:00:00',
                'application_end_date' => '2025-03-31 22:00:00',
                'sort_no' => 1,
            ],
            [
                'lesson_id' => 1,
                'course_category_id' => 15,
                'name' => '年少・年中クラス',
                'description' => '年少・年中のコースです。',
                'course_photo_path' => null,
                'status' => false,
                'application_start_date' => '2024-01-28 10:00:00',
                'application_end_date' => '2025-03-31 22:00:00',
                'sort_no' => 2,
            ],
            [
                'lesson_id' => 1,
                'course_category_id' => 15,
                'name' => '年長・1年生クラス',
                'description' => '年長・1年生のコースです。',
                'course_photo_path' => null,
                'status' => false,
                'application_start_date' => '2024-01-28 10:00:00',
                'application_end_date' => '2025-03-31 22:00:00',
                'sort_no' => 3,
            ],
            [
                'lesson_id' => 1,
                'course_category_id' => 15,
                'name' => '小学生クラス',
                'description' => '小学生のコースです。',
                'course_photo_path' => null,
                'status' => false,
                'application_start_date' => '2024-01-28 10:00:00',
                'application_end_date' => '2025-03-31 22:00:00',
                'sort_no' => 4,
            ],
            [
                'lesson_id' => 1,
                'course_category_id' => 15,
                'name' => '小・中学生クラス',
                'description' => '小・中学生のコースです。',
                'course_photo_path' => null,
                'status' => false,
                'application_start_date' => '2024-01-28 10:00:00',
                'application_end_date' => '2025-03-31 22:00:00',
                'sort_no' => 5,
            ],
            [
                'lesson_id' => 1,
                'course_category_id' => 15,
                'name' => 'キッズアクロクラス',
                'description' => 'キッズアクロのコースです。',
                'course_photo_path' => null,
                'status' => false,
                'application_start_date' => '2024-01-28 10:00:00',
                'application_end_date' => '2025-03-31 22:00:00',
                'sort_no' => 6,
            ],
            [
                'lesson_id' => 1,
                'course_category_id' => 15,
                'name' => 'アクロバットクラス',
                'description' => 'アクロバットのコースです。',
                'course_photo_path' => null,
                'status' => false,
                'application_start_date' => '2024-01-28 10:00:00',
                'application_end_date' => '2025-03-31 22:00:00',
                'sort_no' => 7,
            ],
            [
                'lesson_id' => 1,
                'course_category_id' => 1,
                'name' => '親子体操クラス',
                'description' => '親子体操のコースです。',
                'course_photo_path' => null,
                'status' => true,
                'application_start_date' => '2024-05-05 10:00:00',
                'application_end_date' => '2025-03-31 22:00:00',
                'sort_no' => 8,
            ],
        ]);
    }
}
