export const THEMECOLORS = [
  { color: '#007bff', name: 'blue' },
  { color: '#6610f2', name: 'purple' },
  { color: '#6f42c1', name: 'indigo' },
  { color: '#e83e8c', name: 'pink' },
  { color: '#dc3545', name: 'red' },
  { color: '#fd7e14', name: 'orange' },
  { color: '#ffc107', name: 'yellow' },
  { color: '#28a745', name: 'green' },
  { color: '#20c997', name: 'teal' },
  { color: '#17a2b8', name: 'cyan' },
  { color: '#343a40', name: 'dark' },
  { color: '#6c757d', name: 'secondary' },
  { color: '#007bff', name: 'primary' },
  { color: '#6c757d', name: 'secondary' },
  { color: '#28a745', name: 'success' },
  { color: '#dc3545', name: 'danger' },
  { color: '#ffc107', name: 'warning' },
  { color: '#17a2b8', name: 'info' },
  { color: '#6f42c1', name: 'purple' },
  { color: '#343a40', name: 'dark' },
];
